<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class MediaRepository extends EntityRepository {

    public function myFind() {

        $query = $this->createQueryBuilder('a')
                
                ->getQuery();
        return $query;
    }

 

    public function myFindAll($user_id=null) {

        $query = $this->createQueryBuilder('a')
                   //  ->select('a, f')
               //  ->leftJoin('a.imageMedia', 'f')
              
          
   //   ->select('a')
//  ->leftJoin('a.authorName', 'b')
          
                ->add('orderBy', 'a.id DESC')
              //  ->where('a.proprietaire = :proprietaire')
            //    ->leftJoin('a.proprietaire', 'b')
               // ->leftJoin('a.categorie', 'c')
             //   ->leftJoin('a.idStatus', 'd')
              //  ->setParameter('proprietaire', $user_id)
                ->getQuery()->getResult();

        return $query;

        /* $query = $this->createQueryBuilder('a')
          ->add('orderBy', 'a.id DESC');

          if (isset($user_id)){
          $query=$query->where('a.proprietaire = :proprietaire')
          ->setParameter('proprietaire', $user_id);


          }
          ->getQuery(); */
    }

   
}