epost_indexadmin:
    pattern:  /epostall
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexAll" }

epost:
    pattern:  /blogdashboard
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexdashboard" }
    
epost_indexstandard:
    pattern:  /
    defaults: { _controller: "ApplicationEpostBundle:Epost:standardblog" }
 
epost_indexstandard1:
    pattern:  /design1
    defaults: { _controller: "ApplicationEpostBundle:Epost:standardblog1" }
 
     
epost_index:
    pattern:  /index
    defaults: { _controller: "ApplicationEpostBundle:Epost:index" }
    options:
        expose: true    

epost_indexserch:
    pattern:  /search
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexsearch" }

epost_calendar:
    pattern:  /calendar
    defaults: { _controller: "ApplicationEpostBundle:Epost:CalendarEvents" }
    options:
        expose: true


epost_mesposts:
    pattern:  /mesposts
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexmesposts" }

epost_propositions:
    pattern:  /propositions
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexpropositions" }



        
epost_new:
    pattern:  /new
    defaults: { _controller: "ApplicationEpostBundle:Epost:new" }

epost_create:
    pattern:  /create
    defaults: { _controller: "ApplicationEpostBundle:Epost:create" }
    requirements: { _method: post }

epost_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ApplicationEpostBundle:Epost:edit" }

epost_update:
    pattern:  /{id}/update
    defaults: { _controller: "ApplicationEpostBundle:Epost:update" }
    requirements: { _method: post|put }

epost_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ApplicationEpostBundle:Epost:delete" }
    requirements: { _method: post|delete }

epost_byyear_show:
    pattern:  /index/{year}
    defaults: { _controller: ApplicationEpostBundle:Epost:indexbyyear }
    requirements:
        _method:  GET
        blog_id: \d+
       
epost_addmyimage:
    pattern:  /{id}/addmyimage
    defaults: { _controller: "ApplicationEpostBundle:Epost:addmyimage" }

        

epost_showstandard:
    pattern:  /{blog_id}/{slug}/{comments}
    defaults: { _controller: ApplicationEpostBundle:Epost:show, comments: true }
    requirements:
        _method:  GET
        blog_id: \d+
        
epost_show:
    pattern:  /{blog_id}/{slug}/{comments}
    defaults: { _controller: ApplicationEpostBundle:Epost:show, comments: true }
    requirements:
        _method:  GET
        blog_id: \d+
        
epost_mesposts_testa:
    pattern:  /posttesta
    defaults: { _controller: "ApplicationEpostBundle:Epost:indextesta" }
        
 
epost_mesposts_testb:
    pattern:  /posttestb
    defaults: { _controller: "ApplicationEpostBundle:Epost:indextestb" }
    
     

epost_mesposts_testc:
    pattern:  /posttestc
    defaults: { _controller: "ApplicationEpostBundle:Epost:indextestc" }
      
      

epost_mesposts_testquicksand:
    pattern:  /posttestd
    defaults: { _controller: "ApplicationEpostBundle:Epost:indextestquicksand" }
      

    
epost_mesposts_teste:
    pattern:  /postteste
    defaults: { _controller: "ApplicationEpostBundle:Epost:indextestisotope" }
    